<?php require dirname(__FILE__) . '/../views/head.phtml'?>

	<div class="container1">

		<?php require dirname(__FILE__) . '/../views/navigation.phtml'?>


<section class="container">
		<table class="table table-striped">
		<thead>
			<tr>
			<th scope="col">id</th>
			<th scope="col">Utilisateur</th>
			<th scope="col">Contenu</th>
			<th scope="col">Date de publication</th>
			<th scope="col">Numéro du post</th>
			<th scope="col">Option</th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($comments as $comment){ ?>
			<tr>
			<th scope="row"><?= $comment['id'] ?></th>
			<td><?= $comment['username'] ?></td>
			<td><?= $comment['content'] ?></td>
			<td><?= $comment['publicationDate'] ?></td>
			<td><?= $comment['postId'] ?></td>
			<td><a href="<?= $routes["commentValid"]["lien"] ?><?= $comment['id'] ?>">Valider</a>
				<a href="<?= $routes["commentSupp"]["lien"] ?><?= $comment['id'] ?>">Supprimer</a>
			</td>
			</tr>
		<?php } ?>
		</tbody>
		</table>
		</section>
		</div>
</body>

</html>