<?php require dirname(__FILE__) . '/../views/head.phtml'?>

	<div class="container1">

		<?php require dirname(__FILE__) . '/../views/navigation.phtml'?>


		<section class="container">
		<table class="table table-striped">
		<thead>
			<tr>
			<th scope="col">id</th>
			<th scope="col">Utilisateur</th>
			<th scope="col">bloqué</th>
			nbConnect
			<th scope="col">Option</th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($usrs as $usr){ ?>
			<tr>
			<th scope="row"><?= $usr['id'] ?></td>
			<td><?= $usr['username'] ?></td>
			<td><?= ($usr['nbConnect']>=3)?"oui":"non" ?></td>
			<td>	
			<a href="<?= $routes["dashboardUserdebloque"]["lien"] ?><?= $usr['id'] ?>">débloquer</a>	
			<a href="<?= $routes["dashboardUserDel"]["lien"] ?><?= $usr['id'] ?>">Supprimer</a>
		</td>
			</tr>
		<?php } ?>
		</tbody>
		</table>
		</section>

		<article class="container">
		<div class="row">
		<div class="col">
			<div class="block p-20 form-container">
			<h1>Ajouter un utilisateur</h1>
		<form action="<?=$routes["userAjout"]['lien']?>" method="post">
			<input type="text" name="username" placeholder="Nom d'utilisateur" required autocomplete="off" class="form-control">
			<input type="password" name="password" placeholder="Mot de passe" required class="form-control">
			<button type="submit">S'inscrire</button>
		</form>
		</div>
			</div>
		</div>
		</article>

	</div>


</body>

</html>