<?php require dirname(__FILE__) . '/../views/head.phtml'?>

	<div class="container1">

		<?php require dirname(__FILE__) . '/../views/navigation.phtml'?>


		<section class="container">
		<table class="table table-striped">
		<thead>
			<tr>
			<th scope="col">id</th>
			<th scope="col">Image</th>
			<th scope="col">Option</th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($imgs as $img){ ?>
			<tr>
			<th scope="row"><?= $img['id'] ?></th>
			<td><img src="./uploads/<?=htmlspecialchars($img['image_Path'])?>" alt="<?=htmlspecialchars($img['image_Path'])?>"></td>
			<td><a href="<?= $routes["postSupImgCarrousel"]["lien"] ?><?= $img['id'] ?>">Supprimer</a></td>
			</tr>
		<?php } ?>
		</tbody>
		</table>
		</section>


	
		<article class="container">
		<div class="row">
		<div class="col">
			<div class="block p-20 form-container">

				<h1>Ajouter une immage</h1>
				<form action="<?=$routes["postAjoutImgCarrousel"]['lien']?>" method="post" enctype="multipart/form-data">
				<div >
						<label for="image" class="form-label">Image</label>
						<input type="hidden" name="MAX_FILE_SIZE" value="3000000">
						<input type="file" name="image" accept="image/png, image/jpeg" class="form-control">
						<!-- <p class="text-error"></p> -->
					</div>
					<div >
						<button class="btn btn-secondary" type="button">Annuler</button>
						<button class="btn btn-primary" type="submit">Publier</button>
					</div>
				</form>
			</div>
			</div>
		</div>
		</article>



</body>

</html>