<?php require dirname(__FILE__) . '/../views/head.phtml'?>

	<div class="container1">

		<?php require dirname(__FILE__) . '/../views/navigation.phtml'?>


		<section class="container">
		<table class="table table-striped">
		<thead>
			<tr>
			<th scope="col">id</th>
			<th scope="col">Titre</th>
			<th scope="col">Description</th>
			<th scope="col">Contenu</th>
			<th scope="col">Nom Image</th>
			<th scope="col">Position</th>
			<th scope="col">Date de publication</th>
			<th scope="col">Utilisateur</th>
			<th scope="col">Option</th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($posts as $post){ ?>
			<tr>
			<th scope="row">
					<?= $post['id'] ?>
				</th>
				<td><?= $post['title'] ?></td>
				<td><?= $post['description'] ?></td>
				<td><?= $post['content'] ?></td>
				<td><?= $post['imageFileName'] ?></td>
				<td><?= $post['position'] ?></td>
				<td><?= $post['publicationDate'] ?></td>
				<td><?= $post['writerUsername'] ?></td>
				<td>
					<a href="<?= $routes["postEditArticle"]["lien"] ?><?= $post['id'] ?>">Editer</a>
					<a href="<?= $routes["postSupArticle"]["lien"] ?><?= $post['id'] ?>">Supprimer</a>
				</td>
			</tr>
		<?php } ?>
		</tbody>
		</table>
		
		</section>


	<section class="container">



	<!--<article class="carrousel">

		<div class="col-lg-4 bg-dark rounded px-4">
			<h3 class="text-center text-light p-1"> Selectionner une image pour votre carousel </h3>
			<form action="dashboard.php" method="post" enctype="multipart/form-data">
				<div class="form-group">
					<input type="file" name="image" class="form-control p-1" required>
				</div>
				<div class="class-form-group">
					<input type="submit" name="upload" class="btn btn-warning btn-block" value="Upload Image">
				</div>
				<div class="form-group">
					<h5 class="text-center text-light"><?=$msg;?></h5>
				</div>
			</form>

		</div>
	</article>-->

		<article class="container">
		<div class="row">
		<div class="col">
			<div class="block p-20 form-container">

				<h1>Ecrire un communiqué</h1>
				<?php if($postEC["id"]=="") { ?>
					<form action="<?=$routes["postAjoutArticle"]['lien']?>" method="post" enctype="multipart/form-data">

				<?php } else { ?>
					<form action="<?=$routes["postEditArticle"]['lien']?><?= $postEC["id"]?>" method="post" enctype="multipart/form-data">
					<input type="text" name="id" value="<?= $postEC["id"]?>">
				<?php } ?>
				
					<div >
						<label for="title" class="form-label">Titre</label>
						<input type="text" name="title" placeholder="Titre" required class="form-control" value="<?= $postEC["title"]?>">
						<!-- <p class="text-error"></p> -->
					</div>
					<div >
						<label for="description" class="form-label">Titre</label>
						<input type="text" name="description" placeholder="Description" required class="form-control" value="<?= $postEC["description"]?>">
						<!-- <p class="text-error"></p> -->
					</div>
					<div >
						<label for="image" class="form-label">Image</label>
						<input type="hidden" name="MAX_FILE_SIZE" value="3000000">
						<input type="file" name="image" accept="image/png, image/jpeg" class="form-control">
						<!-- <p class="text-error"></p> -->
					</div>

					<div >
						<label for="category" class="form-label">Sélectionner l'emplacement du communiqué</label>
						<select name="position" id="category" class="form-control">
							<option value="" selected>Choisir la position</option>
							<option value="postGauche">Gauche</option>
							<option value="postCentre">Centre</option>
							<option value="postDroite">Droite</option>
							<!-- <p class="text-error"></p> -->
						</select>
					</div>
					<div >
						<label for="content" class="form-label">Contenu</label>
						<textarea name="content" placeholder="Contenu" required class="form-control" id="tiny">
						<?= $postEC["content"]?></textarea>
						<!-- <p class="text-error"></p> -->
					</div>
					<div >
						<button class="btn btn-secondary" type="button">Annuler</button>
						<button class="btn btn-primary" type="submit">Publier</button>
					</div>
				</form>
			</div>
			</div>
			</div>
		</article>




	</section>

	<script>tinymce.init({selector:'textarea#tiny'});</script>
</body>

</html>