<?php require dirname(__FILE__) . '/../views/head.phtml'?>

	<div class="container1">

		<?php require dirname(__FILE__) . '/../views/navigation.phtml'?>


	<!--	<section class="container">
		<?php foreach ($posts as $post){ ?>
			<div class="row">
				<div class="col">
					<?= $post['id'] ?>
				</div>
				<div class="col">
					<?= $post['title'] ?>
				</div>
				<div class="col">
					<?= $post['content'] ?>
				</div>
				<div class="col">
					<?= $post['imageFileName'] ?>
				</div>
				<div class="col">
					<?= $post['position'] ?>
				</div>
				<div class="col">
					<?= $post['publicationDate'] ?>
				</div>
				<div class="col">
					<?= $post['writerUsername'] ?>
				</div>
				<div class="col">
					option
				</div>
			</div>
		<?php } ?>
		</section>-->


	<section class="container">
			Carrousel non géré


	<!--<article class="carrousel">

		<div class="col-lg-4 bg-dark rounded px-4">
			<h3 class="text-center text-light p-1"> Selectionner une image pour votre carousel </h3>
			<form action="dashboard.php" method="post" enctype="multipart/form-data">
				<div class="form-group">
					<input type="file" name="image" class="form-control p-1" required>
				</div>
				<div class="class-form-group">
					<input type="submit" name="upload" class="btn btn-warning btn-block" value="Upload Image">
				</div>
				<div class="form-group">
					<h5 class="text-center text-light"><?=$msg;?></h5>
				</div>
			</form>

		</div>
	</article>-->

	<!--	<article class="container">
		<div class="row">
		<div class="col">
			<div class="block p-20 form-container">

				<h1>Ecrire un communiqué</h1>

				<form action="<?=$routes["postAjoutArticle"]['lien']?>" method="post" enctype="multipart/form-data">

					<div >
						<label for="title" class="form-label">Titre</label>
						<input type="text" name="title" placeholder="Titre" required class="form-control">
					</div>

					<div >
						<label for="image" class="form-label">Image</label>
						<input type="hidden" name="MAX_FILE_SIZE" value="3000000">
						<input type="file" name="image" accept="image/png, image/jpeg" class="form-control">
					</div>

					<div >
						<label for="category" class="form-label">Sélectionner l'emplacement du communiqué</label>
						<select name="position" id="category" class="form-control">
							<option selected>Choisir la position</option>
							<option value="postGauche">Gauche</option>
							<option value="postCentre">Centre</option>
							<option value="postDroite">Droite</option>
						</select>
					</div>
					<div >
						<label for="content" class="form-label">Contenu</label>
						<textarea name="content" placeholder="Contenu" required class="form-control"></textarea>
					</div>
					<div >
						<button class="btn btn-secondary" type="button">Annuler</button>
						<button class="btn btn-primary" type="submit">Publier</button>
					</div>
				</form>
			</div>
			</div>
			</div>
		</article>
-->



	</section>


</body>

</html>