<?php require dirname(__FILE__) . '/../views/head.phtml'?>

	<div class="container1">

		<?php require dirname(__FILE__) . '/../views/navigation.phtml'?>


		<section class="container">
		<?php foreach ($imgs as $img){ ?>
			<div class="row">
				<div class="col">
					<?= $img['id'] ?>
				</div>
				<div class="col">
					<img src="./uploads/<?=htmlspecialchars($img['image_Path'])?>" alt="<?=htmlspecialchars($img['image_Path'])?>">
				</div>
				<div class="col">
					<a href="<?= $routes["postSupImgCarrousel"]["lien"] ?><?= $img['id'] ?>">Supprimer</a>
				</div>
			</div>
		<?php } ?>
		</section>


	
		<article class="container">
		<div class="row">
		<div class="col">
			<div class="block p-20 form-container">

				<h1>Ajouter une immage</h1>
				<form action="<?=$routes["postAjoutImgCarrousel"]['lien']?>" method="post" enctype="multipart/form-data">
				<div >
						<label for="image" class="form-label">Image</label>
						<input type="hidden" name="MAX_FILE_SIZE" value="3000000">
						<input type="file" name="image" accept="image/png, image/jpeg" class="form-control">
						<!-- <p class="text-error"></p> -->
					</div>
					<div >
						<button class="btn btn-secondary" type="button">Annuler</button>
						<button class="btn btn-primary" type="submit">Publier</button>
					</div>
				</form>
			</div>
			</div>
		</div>
		</article>



</body>

</html>