<footer>
		<a href="https://twitter.com/IsmailOguelleh">
			<i class="fab fa-twitter"></i>
			<span class="not-important">Twitter</span>
		</a>
		<a href="#">
			<i class="fab fa-instagram"></i>
			<span class="not-important">Instagram</span>
		</a>
		<a href="#">
			<i class="fab fa-linkedin"></i>
			<span class="not-important">linkedin</span>
		</a>
		<a href="https://www.facebook.com/PAGEOFFICIELLEIOG">
			<i class="fab fa-facebook"></i>
			<span class="not-important">Facebook</span>
		</a>

		<a href="">
			<i class="fab fa-youtube"></i>
			<span class="not-important">YouTube</span>
		</a>
		<span>2021 Service Presse Présidence © Tous droits réservés</span>
	</footer>
	<script
			  src="https://code.jquery.com/jquery-3.6.0.slim.min.js"
			  integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI="
			  crossorigin="anonymous"></script>
	<script src="./owlcarousel/owl.carousel.min.js"></script>
	<script>
		$(document).ready(function(){
  			$(".owl-carousel").owlCarousel({
				loop:true,
				margin:10,
				autoplay:true,
				autoplayTimeout:3000,
				autoplayHoverPause:true,
				loop:true,
				responsiveClass:true,
				responsive:{
					0:{
						items:1,
						nav:true
					},
					600:{
						items:3,
						nav:true
					},
					1000:{
						items:5,
						nav:true
					}
				}
			});
		});
	</script>
</body>

</html>