<footer>
		<a href="https://www.linkedin.com/in/spp-presse-presidence-1133641b6/" target="_blank">
			<i class="fab fa-linkedin"></i>
			<span class="not-important">linkedin</span>
		</a>
		<a href="https://www.facebook.com/PresidenceDjibouti" target="_blank">
			<i class="fab fa-facebook"></i>
			<span class="not-important">Facebook</span>
		</a>
		<span>2021 Service Presse Présidence © Tous droits réservés</span>
	</footer>
	<script
			  src="https://code.jquery.com/jquery-3.6.0.slim.min.js"
			  integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI="
			  crossorigin="anonymous"></script>
	<script src="./owlcarousel/owl.carousel.min.js"></script>
	<script>
		$(document).ready(function(){
  			$(".owl-carousel").owlCarousel({
				loop:true,
				margin:10,
				autoplay:true,
				autoplayTimeout:3000,
				autoplayHoverPause:true,
				loop:true,
				responsiveClass:true,
				responsive:{
					0:{
						items:1,
						nav:true
					},
					600:{
						items:3,
						nav:true
					},
					1000:{
						items:5,
						nav:true
					}
				}
			});
		});
	</script>
</body>

</html>
