<!DOCTYPE html>
<html lang="fr">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" integrity="undefined" crossorigin="anonymous">
	<link rel="stylesheet" href="./css/index.css">
	<link href="https://fonts.googleapis.com/css?family=Long+Cang|Montserrat:300,400,700&display=swap" rel="stylesheet" />
	<script src="https://kit.fontawesome.com/83f4286022.js" crossorigin="anonymous"></script>
	<link href="https://fonts.googleapis.com/css?family=Cormorant+Garamond|Staatliches&display=swap" rel="stylesheet" />
	<link rel="stylesheet" href="./owlcarousel/assets/owl.carousel.min.css">
	<link rel="stylesheet" href="./owlcarousel/assets/owl.theme.default.min.css">
	<script src="https://cdn.tiny.cloud/1/31eahwute8bfy1tloq8yw09cubvceug6hjvdub6j4k4a950r/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
	<script type='text/javascript' src='https://platform-api.sharethis.com/js/sharethis.js#property=60cbc40d89d72400193eccd5&product=inline-share-buttons' async='async'></script>
	<title><?= $title ?></title>
	<meta name="description" content="<?= $vid["description"] ?>">
	<meta property="og:title" content="<?= $title ?>"/>
	<meta property="og:type" content="website"/>
	<?php $actual_link = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
	$img_og = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http") . "://$_SERVER[HTTP_HOST]/$og_img"; ?>
	<meta property="og:url" content="<?= $actual_link ?>"/>
	<meta property="og:image" content="<?= $img_og ?>"/>
	<meta property="og:description" content="<?= $description ?>"/>
	<!-- <link href="https://vjs.zencdn.net/7.11.4/video-js.css" rel="stylesheet" /> -->
</head>

<body>