<?php require dirname(__FILE__) . '/../views/head.phtml'?>
<?php require dirname(__FILE__) . '/../views/navigation.phtml'?>
<section id="carrousel">
	<div class="owl-carousel">
		<?php foreach ($imgs as $img): ?>
			<img src="./uploads/<?=htmlspecialchars($img['image_Path'])?>">
		<?php endforeach?>
	</div>
</section>
<section class="showcase">
	<?php foreach ($postsGauche as $post): ?>
		<article>
			<a href="<?=$routes["postGetAjout"]['lien']?><?=intval($post['id'])?>">
			<?php if (!empty($post['imageFileName'])): ?>
				<img src="./uploads/<?=htmlspecialchars($post['imageFileName'])?>"
					alt="<?=htmlspecialchars($post['title'])?>">
			<?php endif;?>
			<h3><?=htmlspecialchars($post['title'])?></h3>
			<p>Rédigé par <a href="<?=$routes["postListeArticleRedac"]['lien']?><?=intval($post['writerId'])?>">
				<?=htmlspecialchars($post['writerUsername'])?></a></p>
			<p class="text-hint">le <?=$post['publicationDate']?>
				<i class="fas fa-star mx-1"></i>
			</p>
		</article>
	<?php endforeach?>
	<?php /*var_dump($postsCentre);*/foreach ($postsCentre as $post): ?>
		<article class="article-small">
			<a href="<?=$routes["postGetAjout"]['lien']?><?=intval($post['id'])?>">
			<?php if (!empty($post['imageFileName'])): ?>
				<img src="./uploads/<?=htmlspecialchars($post['imageFileName'])?>" alt="<?=htmlspecialchars($post['title'])?>">
			<?php endif;?>
			<h3><?=htmlspecialchars($post['title'])?></h3>
			<p>Rédigé par <a href="<?=$routes["postListeArticleRedac"]['lien']?><?=intval($post['writerId'])?>">
				<?=htmlspecialchars($post['writerUsername'])?></a></p>
			<br>
			<p class="text-hint">le <?=$post['publicationDate']?>
				<i class="fas fa-star mx-1"></i>
			</p>
		</article>
	<?php endforeach?>
	<?php foreach ($postsDroite as $post): ?>
		<article>
			<a href="<?=$routes["postGetAjout"]['lien']?><?=intval($post['id'])?>">
			<?php if (!empty($post['imageFileName'])): ?>
				<img src="./uploads/<?=htmlspecialchars($post['imageFileName'])?>" alt="<?=htmlspecialchars($post['title'])?>">
			<?php endif;?>
			<h3><?=htmlspecialchars($post['title'])?></h3>
			<p>Rédigé par <a href="<?=$routes["postListeArticleRedac"]['lien']?><?=intval($post['writerId'])?>">
				<?=htmlspecialchars($post['writerUsername'])?></a></p>
			<p class="text-hint">le <?=$post['publicationDate']?>
				<i class="fas fa-star mx-1"></i>
			</p>
		</article>
	<?php endforeach?>
</section>
<section id="videos">
	<?php foreach ($tabJwt as $jwt) {?>
        <video controls src="stream.php?id=<?=$jwt?>" width="300px"></video>
    <?php }?>
</section>
<?php require dirname(__FILE__) . '/../views/foot.phtml'?>