<?php require dirname(__FILE__) . '/../views/head.phtml'?>
<?php require dirname(__FILE__) . '/../views/navigation.phtml'?>
<section id="carrousel">
	<h1>Service de presse de la présidence de Djibouti</h1>
	<div class="owl-carousel">
		<?php foreach ($imgs as $img): ?>
			<img src="./uploads/<?=htmlspecialchars($img['image_Path'])?>">
		<?php endforeach?>
	</div>
</section>
<section id="showcase">
	<h2>Nos articles récents</h2>
	<div class="flex">
	<?php foreach ($postsGauche as $post): ?>
		<article onClick="window.location='<?=$routes["postGetAjout"]['lien']?><?=intval($post['id'])?>'">
			<?php if (!empty($post['imageFileName'])){ ?>
				<img src="./uploads/<?=htmlspecialchars($post['imageFileName'])?>"
					alt="<?=htmlspecialchars($post['title'])?>">
			<?php } else { ?>
				<img src="./img/logo_Service_Presse.jpg" alt="Service Presse Presidence de Djibouti">
			<?php } ?>
			<h3><?=htmlspecialchars($post['title'])?></h3>
			<!-- <p>Rédigé par <?=htmlspecialchars($post['writerUsername'])?></p> -->
			<p class="text-hint">le <?=$post['publicationDate']?>
				<i class="fas fa-star mx-1"></i>
			</p>
		</article>
	<?php endforeach?>
	<div class="centreArt">
		<?php foreach ($postsCentre as $post): ?>
			<article class="article-small" onClick="window.location='<?=$routes["postGetAjout"]['lien']?><?=intval($post['id'])?>'">
				<?php if (!empty($post['imageFileName'])){ ?>
					<img src="./uploads/<?=htmlspecialchars($post['imageFileName'])?>" alt="<?=htmlspecialchars($post['title'])?>">
				<?php } else { ?>
					<img src="./img/logo_Service_Presse.jpg" alt="Service Presse Presidence de Djibouti">
				<?php } ?>
				<div>
					<h3><?=htmlspecialchars($post['title'])?></h3><
					<!-- <p>Rédigé par <?=htmlspecialchars($post['writerUsername'])?></p> -->
					<p class="text-hint">le <?=$post['publicationDate']?>
						<i class="fas fa-star mx-1"></i>
					</p>
				</div>
			</article>
		<?php endforeach?>
	</div>
	<?php foreach ($postsDroite as $post): ?>
		<article onClick="window.location='<?=$routes["postGetAjout"]['lien']?><?=intval($post['id'])?>'">
			<?php if (!empty($post['imageFileName'])){ ?>
				<img src="./uploads/<?=htmlspecialchars($post['imageFileName'])?>" alt="<?=htmlspecialchars($post['title'])?>">
			<?php } else { ?>
				<img src="./img/logo_Service_Presse.jpg" alt="Service Presse Presidence de Djibouti">
			<?php } ?>
			<h3><?=htmlspecialchars($post['title'])?></h3>
			<!-- <p>Rédigé par <?=htmlspecialchars($post['writerUsername'])?></p> -->
			<p class="text-hint">le <?=$post['publicationDate']?>
				<i class="fas fa-star mx-1"></i>
			</p>
		</article>
	<?php endforeach?>
	</div>
</section>
<section id="videos">
	<h2>Nos vidéos récentes</h2>
	<div class="flex">
	<?php foreach ($vids as $vid) {?>
		<article onClick="window.location='<?=$routes["postDetVid"]['lien']?><?=$vid["jwt"]?>'">
		<?php if (!empty($vid['imgvideo_path'])){ ?>
			<img src="./uploads/<?=htmlspecialchars($vid["imgvideo_path"])?>">
		<?php } else { ?>
				<img src="./img/logo_Service_Presse.jpg" alt="Service Presse Presidence de Djibouti">
			<?php } ?>
		<h3><?=htmlspecialchars($vid["titre"])?></h3>
		<!-- <video controls src="stream.php?id=<?=$jwt?>" ></video> -->
		</article>
    <?php }?>
	</div>
</section>
<section id="share">
	<div class="sharethis-inline-share-buttons"></div>
</section>
<?php require dirname(__FILE__) . '/../views/foot.phtml'?>