<header>

	<h1><a href="/" title="Service Presse Presidence de Djibouti"><img id="imgLogo" src="./img/logo_Service_Presse_Noir.jpg" alt="Service Presse Presidence de Djibouti"></a></h1>

		<nav class="desk">

			<!-- <li><a class="text-primary" href="#">Contact</a></li> -->
			<a href="<?=$routes["postGetArticle"]['lien']?>" class="btn btn-light">Accueil</a>
			<a href="<?=$routes["postListeAllArticle"]['lien']?>" class="btn btn-light">Tous les articles</a>
			<a href="<?=$routes["postAllVid"]['lien']?>" class="btn btn-light">Toutes les vidéos</a>
			<a href="<?=$routes["userCon"]['lien']?>" button class="btn btn-light">Connexion</button></a>
			<!--<li><a href="<?=$routes["userAjout"]['lien']?>" button class="btn btn-light">Inscription</button></a></li>-->

		</nav>
		<nav class="mob">
		<a href="<?=$routes["postGetArticle"]['lien']?>" class="btn btn-light"><i class="fas fa-home"></i></a>
			<a href="<?=$routes["postListeAllArticle"]['lien']?>" class="btn btn-light"><i class="fas fa-newspaper"></i></a>
			<a href="<?=$routes["postAllVid"]['lien']?>" class="btn btn-light"><i class="fas fa-film"></i></a>
			<a href="<?=$routes["userCon"]['lien']?>" button class="btn btn-light"><i class="fas fa-user"></i></button></a>
		</nav>
	<?php if (array_key_exists('userId', $_SESSION)): ?>
		<nav>
			<a href="<?=$routes["dashboard"]['lien']?>" class="btn btn-light">Articles</a>
			<a href="<?=$routes["dashboardCarrousel"]['lien']?>" class="btn btn-light">Carrousel</a>
			<a href="<?=$routes["dashboardVideo"]['lien']?>" class="btn btn-light">Vidéos</a>
			<a href="<?=$routes["dashboardUser"]['lien']?>" class="btn btn-light">Utilisateurs</a>
			<a href="<?=$routes["userDeco"]['lien']?>" class="btn btn-light">Déconnexion</a>
		</nav>
	<?php endif;?>

</header>