<header>

	<h1><a href="/" title="Service Presse Presidence de Djibouti"><img src="./img/logo_Service_Presse_Noir.jpg" alt="Service Presse Presidence de Djibouti"></a></h1>

	<?php if (!array_key_exists('userId', $_SESSION)): ?>
		<nav>

			<!-- <li><a class="text-primary" href="#">Contact</a></li> -->
			<a href="<?=$routes["postGetArticle"]['lien']?>" class="btn btn-light">Accueil</a>
			<a href="<?=$routes["userCon"]['lien']?>" button class="btn btn-light">Connexion</button></a>
			<!--<li><a href="<?=$routes["userAjout"]['lien']?>" button class="btn btn-light">Inscription</button></a></li>-->

		</nav>
	<?php else: ?>
		<nav>
			<a href="<?=$routes["postGetArticle"]['lien']?>">Accueil</a>
			<a href="<?=$routes["dashboard"]['lien']?>">Tableau de bord</a>
			<a href="<?=$routes["dashboardCarrousel"]['lien']?>">Gestion du carrousel</a>
			<a href="<?=$routes["dashboardVideo"]['lien']?>">Gestion des vidéos</a>
			<a href="<?=$routes["dashboardUser"]['lien']?>">Gestion des users</a>
			<a href="<?=$routes["userDeco"]['lien']?>">Déconnexion</a>
		</nav>
	<?php endif;?>

</header>