<?php require dirname(__FILE__) . '/../views/head.phtml'?>
<?php require dirname(__FILE__) . '/../views/navigation.phtml'?>
<section id="detArticle">
	<?php if (!empty($post['imageFileName'])) { ?>
		<img src="./uploads/<?=htmlspecialchars($post['imageFileName'])?>" alt="<?=htmlspecialchars($post['title'])?>">
	<?php } else { ?>
		<img src="./img/logo_Service_Presse.jpg" alt="Service Presse Presidence de Djibouti">
	<?php } ?>
	<h1><?=htmlspecialchars($post['title'])?></h1>
	<p><?=$post['content']?></p>
	<p>Post en position : <?=htmlspecialchars($post['position'])?></p>
	<p>Rédigé par <?=htmlspecialchars($post['writerUsername'])?></p>
	<p class="text-hint">le <?=$post['publicationDate']?></p>
	<div class="sharethis-inline-share-buttons"></div>
</section>
<?php require dirname(__FILE__) . '/../views/foot.phtml'?>