<?php require dirname(__FILE__) . '/../views/head.phtml'?>

	<div class="container-fluid">

		<?php require dirname(__FILE__) . '/../views/navigation.phtml'?>
		</br></br>

			<section>
			<!--	<a href="<?=$routes["postGetAjout"]['lien']?><?=intval($post['id'])?>">-->

				

					<h1><?=htmlspecialchars($post['title'])?></h1>

					<?php if (!is_null($post['imageFileName'])): ?>
						<img src="./uploads/<?=htmlspecialchars($post['imageFileName'])?>" alt="<?=htmlspecialchars($post['title'])?>">
					<?php endif;?>

					<p><?=$post['content']?></p>

					<p>Post en position : <?=htmlspecialchars($post['position'])?></p>

					<p>Rédigé par <a href="<?=$routes["postListeArticleRedac"]['lien']?><?=intval($post['writerId'])?>">
							<?=htmlspecialchars($post['writerUsername'])?></a></p>
					<p class="text-hint">le <?=$post['publicationDate']?></p>

			</section>


		</br></br>

		<?php
if (isset($success)) {
    echo $success;
}

if (!empty($errors)): ?>
			<?php foreach ($errors as $error): ?>
				<div class="row">
					<div class="col-md-6">
						<div class="alert alert-danger">
							<?=$error?>
						</div>
					</div>
				</div>
			<?php endforeach;?>
		<?php endif;?>


	</div>
	<?php require dirname(__FILE__) . '/../views/foot.phtml'?>