<!DOCTYPE html>
<html lang="fr">

<head>
	<meta charset="utf-8">
	<title>Blog : Identification</title>
	<link rel="stylesheet" href="../css/connexion.css">
</head>

<body>






	<div class="login-page">
		<div class="form">
			<form action="<?=$routes["userCon"]['lien']?>" method="post">
				<input type="email" name="email" placeholder="Nom d'utilisateur" required autocomplete="off">
				<input type="password" name="password" placeholder="Mot de passe" required>
				<button type="submit">Connexion</button>
			</form>
		</div>
	</div>


</body>

</html>
