<?php require dirname(__FILE__) . '/../views/head.phtml'?>
<?php require dirname(__FILE__) . '/../views/navigation.phtml'?>
<section id="detArticle">
	<canvas id="vid" data-vid="stream.php?id=<?=$jwt?>"></canvas>
	<!-- <script>
		
		let fich = "stream.php?id=<?=$jwt?>"
	</script> -->
	<script src="./js/testLect.js"></script>
	
</section>
<script src="https://vjs.zencdn.net/7.11.4/video.min.js"></script>
<?php require dirname(__FILE__) . '/../views/foot.phtml'?>