<?php require dirname(__FILE__) . '/../views/head.phtml'?>
<?php require dirname(__FILE__) . '/../views/navigation.phtml'?>
<section id="detArticle">
	<video 
	class="video-js"
	controls
	preload="auto">
	<source src="stream.php?id=<?=$jwt?>" type="video/mp4" />
	</video>
</section>
<script src="https://vjs.zencdn.net/7.11.4/video.min.js"></script>
<?php require dirname(__FILE__) . '/../views/foot.phtml'?>