<?php require dirname(__FILE__) . '/../views/head.phtml'?>
<div class="container-fluid">
		<?php require dirname(__FILE__) . '/../views/navigation.phtml'?>
		<h1>Articles rédigés par <?=htmlspecialchars($writer['username'])?></h1>
		<?php foreach ($posts as $post): ?>


			<a href="<?=$routes["postGetAjout"]['lien']?><?=intval($post['id'])?>">
				<h3><?=htmlspecialchars($post['title'])?></h3>
			</a>
			<?php if (!is_null($post['imageFileName'])): ?>
				<img src="./uploads/<?=htmlspecialchars($post['imageFileName'])?>" alt="<?=htmlspecialchars($post['title'])?>">
			<?php endif;?>
			<p>Rédigé par <a href="<?=$routes["postListeArticleRedac"]['lien']?><?= intval($post['writerId']) ?>"><?=htmlspecialchars($post['writerUsername'])?></a>, le <?=$post['publicationDate']?></p>
		<?php endforeach;?>
		</div>
		<?php require dirname(__FILE__) . '/../views/foot.phtml'?>